/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keyboard;

import com.jtattoo.plaf.smart.SmartLookAndFeel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Meelon
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     *
     */
    JFileChooser chooser = new JFileChooser();
    BufferedImage img;
    String filename;
    File file;
    ImageIcon icon = null;
    int tl;
//    Toolkit width = (Toolkit) Toolkit.getDefaultToolkit().getDesktopProperty(String.valueOf(getWidth()));
//    Toolkit height = (Toolkit) Toolkit.getDefaultToolkit().getDesktopProperty(String.valueOf(getHeight()));

    public Welcome() {
        //setSize(Toolkit.getDefaultToolkit(width), Toolkit.getDefaultToolkit(height));

       // this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setFocusable(false);

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Welcome to Easy Typing");

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(204, 204, 255));
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Enter Your Name");

        image.setBackground(new java.awt.Color(153, 153, 153));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboard/images/images (3).jpg"))); // NOI18N
        image.setIconTextGap(0);

        jButton2.setText("Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Time");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01:00 m", "02:00 m", "03:00 m", "05:00 m" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = name.getText();
        String timelength = jComboBox1.getSelectedItem().toString();

        if ((name.getText().trim()).equals("")) {
            String error = "Enter your name";
            JOptionPane.showMessageDialog(rootPane, error);

        } else {
            if ("01:00 m".equals(timelength)) {
                tl = 60000;
                // System.out.println(tl);
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else if ("02:00 m".equals(timelength)) {
                tl = 120000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else if ("02:00 m".equals(timelength)) {
                tl = 180000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else {
                tl = 300000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

        String user = name.getText();
        String timelength = jComboBox1.getSelectedItem().toString();

        if ((name.getText().trim()).equals("")) {
            String error = "Enter your name";
            JOptionPane.showMessageDialog(rootPane, error);

        } else {
            if ("01:00 m".equals(timelength)) {
                tl = 60000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else if ("02:00 m".equals(timelength)) {
                tl = 120000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else if ("02:00 m".equals(timelength)) {
                tl = 180000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            } else {
                tl = 300000;
                new KeyBoardType(user, icon, tl).setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();

        try {
            img = ImageIO.read(file);

            icon = new ImageIcon(img.getScaledInstance(image.getHeight(), image.getWidth(), Image.SCALE_DEFAULT));

            image.setIcon(icon);
            Dimension dimension = new Dimension(icon.getIconWidth(), icon.getIconHeight());
            image.setPreferredSize(dimension);

            image.revalidate();
            image.repaint();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
//
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//
//        }
    }//GEN-LAST:event_nameKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     * @return
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//                //UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
//                // select the Look and Feel
//                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");

                // setup the look and feel properties
//                Properties props = new Properties();
//
//                props.put("logoString", "my company");
//                props.put("licenseKey", "INSERT YOUR LICENSE KEY HERE");
//
//                props.put("selectionBackgroundColor", "180 240 197");
//                props.put("menuSelectionBackgroundColor", "180 240 197");
//
//                props.put("controlColor", "218 254 230");
//                props.put("controlColorLight", "218 254 230");
//                props.put("controlColorDark", "180 240 197");
//
//                props.put("buttonColor", "218 230 254");
//                props.put("buttonColorLight", "255 255 255");
//                props.put("buttonColorDark", "244 242 232");
//
//                props.put("rolloverColor", "218 254 230");
//                props.put("rolloverColorLight", "218 254 230");
//                props.put("rolloverColorDark", "180 240 197");
//
//                props.put("windowTitleForegroundColor", "0 0 0");
//                props.put("windowTitleBackgroundColor", "180 240 197");
//                props.put("windowTitleColorLight", "218 254 230");
//                props.put("windowTitleColorDark", "180 240 197");
//                props.put("windowBorderColor", "218 254 230");
//
//                // set your theme
//                SmartLookAndFeel.setCurrentTheme(props);
                // select the Look and Feel
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
